### ISSUE TITLE
One Page Write-Up.

### ISSUE THREAD

**Issue by maniacGhost24** [Eakadmik2/Eakadmik2#2]
Create a one-page write up, introducing the team, documenting our problem statement and what we aim to create in the project.

- [ ] Create and upload the write-up.

**Comment by shishir-code** [comment]
[Engineering Analysis and Design- One Page Write-up.pdf](https://github.com/Eakadmik2/Eakadmik2/files/6117623/Engineering.Analysis.and.Design-.One.Page.Write-up.pdf)

suggestions and editing by @maniacGhost24

**Comment by shishir-code** [comment]
[Engineering Analysis and Design- One Page Write-up.pdf](https://github.com/Eakadmik2/Eakadmik2/files/6117661/Engineering.Analysis.and.Design-.One.Page.Write-up.pdf)
suggestion and editing by @maniacGhost24
